show databases;
USE INTERNdb;

CREATE TABLE PRODUCTS_HARIKA (PRODUCT_ID INT,PRODUCT_NAME varchar(30),PRICE INT);
INSERT INTO PRODUCTS_HARIKA (PRODUCT_ID,PRODUCT_NAME,PRICE) VALUES (101,'EAR PHONES',2500) ,(102,'SMART WATCH',3999),(103,'MOBILE',15999);
INSERT INTO PRODUCTS_HARIKA (PRODUCT_ID,PRODUCT_NAME,PRICE)  VALUES (104,'MOUSE',999);
SELECT * FROM PRODUCTS_HARIKA;

ALTER TABLE PRODUCTS_HARIKA ADD COLUMN WARRANTY_DATE DATE;
update PRODUCTS_HARIKA SET WARRANTY_DATE = '2025-02-19' WHERE PRODUCT_ID=101;
update PRODUCTS_HARIKA SET WARRANTY_DATE = '2024-02-27' WHERE PRODUCT_ID=102;
update PRODUCTS_HARIKA SET WARRANTY_DATE = '2023-05-12' WHERE PRODUCT_ID=103;
update PRODUCTS_HARIKA SET WARRANTY_DATE = '2026-12-23' WHERE PRODUCT_ID=104;

create table users_harika ( userid varchar(10) primary key, uName varchar(30),uPhone long,user_email varchar(40));
insert into users_harika (userid,uname,uphone,user_email) values ('U2','John',1235666767,'j@gamil.com');
ALTER TABLE USERS_HARIKA ADD COLUMN USERNAME varchar(30);
UPDATE USERS_HARIKA SET USERNAME = "admin" WHERE USERID = 'U1';

ALTER TABLE USERS_HARIKA ADD COLUMN PASSWORD varchar(30);
UPDATE USERS_HARIKA SET PASSWORD = "pass123" WHERE USERID = 'U1';
SELECT * FROM USERS_HARIKA;

ALTER TABLE USERS_HARIKA MODIFY COLUMN UPHONE varchar(10);

create table items (name varchar(30),description varchar(100));
SELECT *FROM ITEMS;